FROM node:20-alpine

WORKDIR /app

ENV HUSKY=0

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.nest.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY apps/realtime-gateway/package.json ./apps/realtime-gateway/package.json

RUN pnpm install --frozen-lockfile

COPY apps/realtime-gateway ./apps/realtime-gateway

WORKDIR /app/apps/realtime-gateway

CMD ["pnpm", "start:dev"]
