packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  bcrypt: true
  prisma: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - bcrypt
  - prisma
