FROM node:20-alpine

WORKDIR /app

ENV HUSKY=0

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.nest.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY apps/matchmaking-service/package.json ./apps/matchmaking-service/package.json

RUN pnpm install --frozen-lockfile

COPY apps/matchmaking-service ./apps/matchmaking-service

WORKDIR /app/apps/matchmaking-service

CMD ["pnpm", "start:dev"]
