FROM node:22-alpine

WORKDIR /app

ENV HUSKY=0

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.nest.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY apps/user-service/package.json ./apps/user-service/package.json

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @whoshuman/shared-events build

COPY apps/user-service ./apps/user-service

WORKDIR /app/apps/user-service

CMD ["pnpm", "start:dev"]
