FROM node:22-alpine

WORKDIR /app

ENV HUSKY=0

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.nest.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY apps/auth-service/package.json ./apps/auth-service/package.json

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @whoshuman/shared-events build && pnpm --filter @whoshuman/shared-types build

COPY apps/auth-service ./apps/auth-service

WORKDIR /app/apps/auth-service

CMD ["pnpm", "start:dev"]
