FROM node:22-alpine

WORKDIR /app

ENV HUSKY=0

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.nest.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY apps/notification-service/package.json ./apps/notification-service/package.json

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @whoshuman/shared-events build && pnpm --filter @whoshuman/shared-types build

COPY apps/notification-service ./apps/notification-service

WORKDIR /app/apps/notification-service

CMD ["pnpm", "start:dev"]
